server:
  port: 8080
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/swagger-docx
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    com.dqv5: debug
    com.deepoove: warn
